记录时间：2017-12-08 17:09:04,803 
线程ID:[5] 
日志级别：  ERROR 
出错类：ZCSAPI.Log4Net.LogHelper property: [(null)] 
错误描述：System.Web.Http.HttpResponseException: 处理 HTTP 请求导致了异常。请参见此异常的 "Response" 属性返回的 HTTP 响应，以了解详细信息。
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.HandleUnauthorizedRequest(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 124
   在 ZCSAPI.App_Start.BasicAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext) 位置 E:\zcsgit\ZCSAPI\ZCSAPI\App_Start\BasicAuthorizeAttribute.cs:行号 65
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() 


